=== maarkkx/DAW-1/marques/nf4/PP_Gras_Mark/ex1/ex1mg.dtd
<!ELEMENT llibreria (llibre+)>

<!ELEMENT llibre (titol, autor+, ISBN, editorial?, any_publicacio, categories*,preu?)>

<!ELEMENT titol (#PCDATA)>

<!ELEMENT autor (#PCDATA)>

<!ELEMENT ISBN (#PCDATA)>
<!ATTLIST ISBN id ID #REQUIRED>

<!ELEMENT editorial (#PCDATA)>

<!ELEMENT any_publicacio (#PCDATA)>

<!ELEMENT categories (categoria+)>

<!ELEMENT categoria (#PCDATA)>

<!ELEMENT preu (#PCDATA)>
<!ATTLIST preu moneda (EUR|USD) #REQUIRED>

=== maarkkx/DAW-1/marques/nf4/PP_Gras_Mark/ex1/ex1mg.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE llibreria SYSTEM "EX1MG.dtd">
<llibreria>
    <llibre>
        <titol>Harry Potter</titol>
        <autor>J.K. Rolling</autor>
        <ISBN id="A1">1</ISBN>
        <editorial>si</editorial>
        <any_publicacio>2000</any_publicacio>
        <categories>
            <categoria>Accio</categoria>
            <categoria>Fantasia</categoria>
        </categories>
        <preu moneda="EUR">20</preu>
    </llibre>
    <llibre>
        <titol>geronimo stilton</titol>
        <autor>Si</autor>
        <ISBN id="A2">2</ISBN>
        <editorial>si</editorial>
        <any_publicacio>2004</any_publicacio>
        <categories>
            <categoria>Accio</categoria>
            <categoria>Misteri</categoria>
        </categories>
        <preu moneda="EUR">15</preu>
    </llibre>
</llibreria>
